# Site settings
title: Diogo Moreira
email: diogo.dmoreira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Diogo Moreira's personal blog. Posts and articles about software development,
  games, travels and so forth.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diogodmoreira.com" # the base hostname & protocol for your site
twitter_username: diogodmoreira
github_username:  diogomoreira

# Build settings
markdown: kramdown
